# Generated by Django 5.2.16 on 2026-07-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft / Created'), ('sent', 'Sent to Customer'), ('approved', 'Approved by Customer'), ('converted', 'Converted to Order'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('template_name', models.CharField(choices=[('standard', 'Standard Rental Template'), ('corporate', 'Corporate Partner Deal'), ('special_event', 'Wedding & Special Event Deal')], default='standard', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Quoted unit rate', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation')),
                ('rental_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rentalperiod')),
            ],
        ),
    ]
