# Generated by Django 5.2.16 on 2026-07-18 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quotation', 'Quotation'), ('confirmed', 'Confirmed / Reserved'), ('picked_up', 'Picked Up / Active'), ('returned', 'Returned / Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateTimeField(help_text='Scheduled pickup start date and time')),
                ('return_date', models.DateTimeField(help_text='Scheduled return end date and time')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('security_deposit_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Customer Pickup'), ('delivery', 'Delivery to Address')], default='pickup', max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit Paid Only'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('checklist_condition_checked', models.BooleanField(default=False, help_text='Verify product condition before pickup')),
                ('checklist_id_verified', models.BooleanField(default=False, help_text='Verify customer identity document')),
                ('checklist_agreement_signed', models.BooleanField(default=False, help_text='Customer signed rental agreement')),
                ('qr_code_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_pickups', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_details', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='LateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_overdue', models.IntegerField(help_text='Overdue count (e.g. days/hours depending on unit)')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment / Deduction'), ('deducted', 'Deducted from Deposit'), ('paid', 'Paid Separately')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fees', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1, help_text='Number of units of the selected rental period')),
                ('price', models.DecimalField(decimal_places=2, help_text='Rental rate at checkout', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rentalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('rental_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rentalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('checklist_damage_checked', models.BooleanField(default=False, help_text='Verify product for damages upon return')),
                ('checklist_accessories_present', models.BooleanField(default=False, help_text='Verify all parts/accessories returned')),
                ('damage_report', models.TextField(blank=True, null=True)),
                ('missing_accessories', models.TextField(blank=True, null=True)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refunded_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('repair_workflow_status', models.CharField(choices=[('none', 'No Damages'), ('pending', 'Repair Assessment Pending'), ('repaired', 'Repaired & Settled')], default='none', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('refunded', 'Fully Refunded'), ('deducted', 'Partially Deducted / Settled')], default='collected', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='rentals.rentalorder')),
            ],
        ),
    ]
