# Generated by Django 5.2.16 on 2026-07-19
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('rentals', '0001_initial')]
    operations = [
        migrations.AddField(model_name='rentalorder', name='created_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rental_orders', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='rentalorder', name='order_type', field=models.CharField(choices=[('online', 'Online Order'), ('walk_in', 'Walk-in Order')], default='online', max_length=10)),
        migrations.AddField(model_name='rentalorder', name='rental_days', field=models.PositiveIntegerField(default=1, help_text='Number of rental days')),
    ]
