# Generated by Django 5.2.16 on 2026-07-19
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('customers', '0001_initial')]
    operations = [
        migrations.AddField(model_name='customer', name='is_walk_in', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='customer', name='walk_in_name', field=models.CharField(blank=True, max_length=200, null=True)),
        migrations.AlterField(model_name='customer', name='user', field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
    ]
